/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashRouteRouteImport } from './routes/_dash/route'
import { Route as DashIndexRouteImport } from './routes/_dash/index'
import { Route as ProductsAddRouteImport } from './routes/products.add'
import { Route as DashSandboxRouteImport } from './routes/_dash/sandbox'
import { Route as DashReviewProductsRouteImport } from './routes/_dash/review-products'
import { Route as DashCustomersRouteImport } from './routes/_dash/customers'
import { Route as DashCategoriesRouteImport } from './routes/_dash/categories'
import { Route as DashBrandsRouteImport } from './routes/_dash/brands'
import { Route as DashAnalyticsRouteImport } from './routes/_dash/analytics'
import { Route as DashPurchasesIndexRouteImport } from './routes/_dash/purchases.index'
import { Route as DashProductsIndexRouteImport } from './routes/_dash/products.index'
import { Route as DashOrdersIndexRouteImport } from './routes/_dash/orders.index'
import { Route as DashPurchasesAddRouteImport } from './routes/_dash/purchases.add'
import { Route as DashPurchasesIdRouteImport } from './routes/_dash/purchases.$id'
import { Route as DashProductsIdRouteImport } from './routes/_dash/products.$id'
import { Route as DashOrdersAddRouteImport } from './routes/_dash/orders.add'
import { Route as DashOrdersIdRouteImport } from './routes/_dash/orders.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRouteRoute = DashRouteRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRouteRoute,
} as any)
const ProductsAddRoute = ProductsAddRouteImport.update({
  id: '/products/add',
  path: '/products/add',
  getParentRoute: () => rootRouteImport,
} as any)
const DashSandboxRoute = DashSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashReviewProductsRoute = DashReviewProductsRouteImport.update({
  id: '/review-products',
  path: '/review-products',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashCustomersRoute = DashCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashCategoriesRoute = DashCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashBrandsRoute = DashBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashAnalyticsRoute = DashAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashPurchasesIndexRoute = DashPurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashProductsIndexRoute = DashProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashOrdersIndexRoute = DashOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashPurchasesAddRoute = DashPurchasesAddRouteImport.update({
  id: '/purchases/add',
  path: '/purchases/add',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashPurchasesIdRoute = DashPurchasesIdRouteImport.update({
  id: '/purchases/$id',
  path: '/purchases/$id',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashProductsIdRoute = DashProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashOrdersAddRoute = DashOrdersAddRouteImport.update({
  id: '/orders/add',
  path: '/orders/add',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashOrdersIdRoute = DashOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => DashRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/analytics': typeof DashAnalyticsRoute
  '/brands': typeof DashBrandsRoute
  '/categories': typeof DashCategoriesRoute
  '/customers': typeof DashCustomersRoute
  '/review-products': typeof DashReviewProductsRoute
  '/sandbox': typeof DashSandboxRoute
  '/products/add': typeof ProductsAddRoute
  '/': typeof DashIndexRoute
  '/orders/$id': typeof DashOrdersIdRoute
  '/orders/add': typeof DashOrdersAddRoute
  '/products/$id': typeof DashProductsIdRoute
  '/purchases/$id': typeof DashPurchasesIdRoute
  '/purchases/add': typeof DashPurchasesAddRoute
  '/orders': typeof DashOrdersIndexRoute
  '/products': typeof DashProductsIndexRoute
  '/purchases': typeof DashPurchasesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof DashAnalyticsRoute
  '/brands': typeof DashBrandsRoute
  '/categories': typeof DashCategoriesRoute
  '/customers': typeof DashCustomersRoute
  '/review-products': typeof DashReviewProductsRoute
  '/sandbox': typeof DashSandboxRoute
  '/products/add': typeof ProductsAddRoute
  '/': typeof DashIndexRoute
  '/orders/$id': typeof DashOrdersIdRoute
  '/orders/add': typeof DashOrdersAddRoute
  '/products/$id': typeof DashProductsIdRoute
  '/purchases/$id': typeof DashPurchasesIdRoute
  '/purchases/add': typeof DashPurchasesAddRoute
  '/orders': typeof DashOrdersIndexRoute
  '/products': typeof DashProductsIndexRoute
  '/purchases': typeof DashPurchasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dash': typeof DashRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_dash/analytics': typeof DashAnalyticsRoute
  '/_dash/brands': typeof DashBrandsRoute
  '/_dash/categories': typeof DashCategoriesRoute
  '/_dash/customers': typeof DashCustomersRoute
  '/_dash/review-products': typeof DashReviewProductsRoute
  '/_dash/sandbox': typeof DashSandboxRoute
  '/products/add': typeof ProductsAddRoute
  '/_dash/': typeof DashIndexRoute
  '/_dash/orders/$id': typeof DashOrdersIdRoute
  '/_dash/orders/add': typeof DashOrdersAddRoute
  '/_dash/products/$id': typeof DashProductsIdRoute
  '/_dash/purchases/$id': typeof DashPurchasesIdRoute
  '/_dash/purchases/add': typeof DashPurchasesAddRoute
  '/_dash/orders/': typeof DashOrdersIndexRoute
  '/_dash/products/': typeof DashProductsIndexRoute
  '/_dash/purchases/': typeof DashPurchasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/analytics'
    | '/brands'
    | '/categories'
    | '/customers'
    | '/review-products'
    | '/sandbox'
    | '/products/add'
    | '/'
    | '/orders/$id'
    | '/orders/add'
    | '/products/$id'
    | '/purchases/$id'
    | '/purchases/add'
    | '/orders'
    | '/products'
    | '/purchases'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/brands'
    | '/categories'
    | '/customers'
    | '/review-products'
    | '/sandbox'
    | '/products/add'
    | '/'
    | '/orders/$id'
    | '/orders/add'
    | '/products/$id'
    | '/purchases/$id'
    | '/purchases/add'
    | '/orders'
    | '/products'
    | '/purchases'
  id:
    | '__root__'
    | '/_dash'
    | '/login'
    | '/_dash/analytics'
    | '/_dash/brands'
    | '/_dash/categories'
    | '/_dash/customers'
    | '/_dash/review-products'
    | '/_dash/sandbox'
    | '/products/add'
    | '/_dash/'
    | '/_dash/orders/$id'
    | '/_dash/orders/add'
    | '/_dash/products/$id'
    | '/_dash/purchases/$id'
    | '/_dash/purchases/add'
    | '/_dash/orders/'
    | '/_dash/products/'
    | '/_dash/purchases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashRouteRoute: typeof DashRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProductsAddRoute: typeof ProductsAddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/': {
      id: '/_dash/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/products/add': {
      id: '/products/add'
      path: '/products/add'
      fullPath: '/products/add'
      preLoaderRoute: typeof ProductsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/sandbox': {
      id: '/_dash/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof DashSandboxRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/review-products': {
      id: '/_dash/review-products'
      path: '/review-products'
      fullPath: '/review-products'
      preLoaderRoute: typeof DashReviewProductsRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/customers': {
      id: '/_dash/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof DashCustomersRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/categories': {
      id: '/_dash/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof DashCategoriesRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/brands': {
      id: '/_dash/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof DashBrandsRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/analytics': {
      id: '/_dash/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashAnalyticsRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/purchases/': {
      id: '/_dash/purchases/'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof DashPurchasesIndexRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/products/': {
      id: '/_dash/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof DashProductsIndexRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/orders/': {
      id: '/_dash/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof DashOrdersIndexRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/purchases/add': {
      id: '/_dash/purchases/add'
      path: '/purchases/add'
      fullPath: '/purchases/add'
      preLoaderRoute: typeof DashPurchasesAddRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/purchases/$id': {
      id: '/_dash/purchases/$id'
      path: '/purchases/$id'
      fullPath: '/purchases/$id'
      preLoaderRoute: typeof DashPurchasesIdRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/products/$id': {
      id: '/_dash/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof DashProductsIdRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/orders/add': {
      id: '/_dash/orders/add'
      path: '/orders/add'
      fullPath: '/orders/add'
      preLoaderRoute: typeof DashOrdersAddRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/orders/$id': {
      id: '/_dash/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof DashOrdersIdRouteImport
      parentRoute: typeof DashRouteRoute
    }
  }
}

interface DashRouteRouteChildren {
  DashAnalyticsRoute: typeof DashAnalyticsRoute
  DashBrandsRoute: typeof DashBrandsRoute
  DashCategoriesRoute: typeof DashCategoriesRoute
  DashCustomersRoute: typeof DashCustomersRoute
  DashReviewProductsRoute: typeof DashReviewProductsRoute
  DashSandboxRoute: typeof DashSandboxRoute
  DashIndexRoute: typeof DashIndexRoute
  DashOrdersIdRoute: typeof DashOrdersIdRoute
  DashOrdersAddRoute: typeof DashOrdersAddRoute
  DashProductsIdRoute: typeof DashProductsIdRoute
  DashPurchasesIdRoute: typeof DashPurchasesIdRoute
  DashPurchasesAddRoute: typeof DashPurchasesAddRoute
  DashOrdersIndexRoute: typeof DashOrdersIndexRoute
  DashProductsIndexRoute: typeof DashProductsIndexRoute
  DashPurchasesIndexRoute: typeof DashPurchasesIndexRoute
}

const DashRouteRouteChildren: DashRouteRouteChildren = {
  DashAnalyticsRoute: DashAnalyticsRoute,
  DashBrandsRoute: DashBrandsRoute,
  DashCategoriesRoute: DashCategoriesRoute,
  DashCustomersRoute: DashCustomersRoute,
  DashReviewProductsRoute: DashReviewProductsRoute,
  DashSandboxRoute: DashSandboxRoute,
  DashIndexRoute: DashIndexRoute,
  DashOrdersIdRoute: DashOrdersIdRoute,
  DashOrdersAddRoute: DashOrdersAddRoute,
  DashProductsIdRoute: DashProductsIdRoute,
  DashPurchasesIdRoute: DashPurchasesIdRoute,
  DashPurchasesAddRoute: DashPurchasesAddRoute,
  DashOrdersIndexRoute: DashOrdersIndexRoute,
  DashProductsIndexRoute: DashProductsIndexRoute,
  DashPurchasesIndexRoute: DashPurchasesIndexRoute,
}

const DashRouteRouteWithChildren = DashRouteRoute._addFileChildren(
  DashRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashRouteRoute: DashRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ProductsAddRoute: ProductsAddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
