/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashRouteRouteImport } from './routes/_dash/route'
import { Route as DashIndexRouteImport } from './routes/_dash/index'
import { Route as DashProductsRouteImport } from './routes/_dash/products'
import { Route as DashOrdersRouteImport } from './routes/_dash/orders'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRouteRoute = DashRouteRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashProductsRoute = DashProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashOrdersRoute = DashOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/orders': typeof DashOrdersRoute
  '/products': typeof DashProductsRoute
  '/': typeof DashIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/orders': typeof DashOrdersRoute
  '/products': typeof DashProductsRoute
  '/': typeof DashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dash': typeof DashRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_dash/orders': typeof DashOrdersRoute
  '/_dash/products': typeof DashProductsRoute
  '/_dash/': typeof DashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/orders' | '/products' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/orders' | '/products' | '/'
  id:
    | '__root__'
    | '/_dash'
    | '/login'
    | '/_dash/orders'
    | '/_dash/products'
    | '/_dash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashRouteRoute: typeof DashRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/': {
      id: '/_dash/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/products': {
      id: '/_dash/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof DashProductsRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/orders': {
      id: '/_dash/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof DashOrdersRouteImport
      parentRoute: typeof DashRouteRoute
    }
  }
}

interface DashRouteRouteChildren {
  DashOrdersRoute: typeof DashOrdersRoute
  DashProductsRoute: typeof DashProductsRoute
  DashIndexRoute: typeof DashIndexRoute
}

const DashRouteRouteChildren: DashRouteRouteChildren = {
  DashOrdersRoute: DashOrdersRoute,
  DashProductsRoute: DashProductsRoute,
  DashIndexRoute: DashIndexRoute,
}

const DashRouteRouteWithChildren = DashRouteRoute._addFileChildren(
  DashRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashRouteRoute: DashRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
