import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

type ProductImage = { url: string; isPrimary?: boolean };

type Product = {
	sourceId: number;
	name: string;
	slug: string;
	description: string;
	status: string;
	discount: number;
	amount: string;
	potency: string;
	stock: number;
	price: number;
	dailyIntake: number;
	category: string;
	brand: string;
	tags?: string[];
	isFeatured?: boolean;
	ingredients?: string[];
	seoTitle?: string | null;
	seoDescription?: string | null;
	nameMn?: string | null;
	weightGrams?: number | null;
	createdAt?: string;
	images?: ProductImage[];
};

type ProductFile = {
	generatedAt: string;
	count: number;
	products: Product[];
};

const slugify = (value: string): string =>
	value
		.toLowerCase()
		.normalize("NFKD")
		.replace(/[^a-z0-9\s-]/g, "")
		.replace(/\s+/g, "-")
		.replace(/-+/g, "-")
		.replace(/^-|-$/g, "")
		.slice(0, 120);

function main() {
	const root = process.cwd();
	const inputPath = resolve(root, "products.json");
	const outputPath = resolve(root, "apps/server/seed.sql");
	const reportPath = resolve(root, "generated/seed-build-report.json");

	const data = JSON.parse(readFileSync(inputPath, "utf-8")) as ProductFile;
	const products = data.products ?? [];

	const brands = Array.from(
		new Set(products.map((p) => (p.brand || "").trim()).filter(Boolean)),
	).sort((a, b) => a.localeCompare(b));
	const categories = Array.from(
		new Set(products.map((p) => (p.category || "").trim()).filter(Boolean)),
	).sort((a, b) => a.localeCompare(b));

	const brandRows = brands.map((name) => ({
		name,
		logo_url: `https://cdn.darjs.dev/brands/${slugify(name)}.webp`,
	}));

	const productRows = products.map((p, idx) => ({
		source_id: p.sourceId,
		name: p.name,
		slug: p.slug,
		description: p.description || "",
		status: p.status || "active",
		discount: Number.isFinite(p.discount) ? p.discount : 0,
		amount: p.amount || "N/A",
		potency: p.potency || "N/A",
		stock: Number.isFinite(p.stock) ? p.stock : 1,
		price: Number.isFinite(p.price) ? p.price : 0,
		daily_intake: Number.isFinite(p.dailyIntake) ? p.dailyIntake : 1,
		category: p.category,
		brand: p.brand,
		tags: Array.isArray(p.tags) ? p.tags : [],
		is_featured: Boolean(p.isFeatured),
		ingredients: Array.isArray(p.ingredients) ? p.ingredients : [],
		seo_title: p.seoTitle || p.name,
		seo_description: p.seoDescription || p.name,
		name_mn: p.nameMn ?? null,
		weight_grams: Number.isFinite(p.weightGrams as number)
			? (p.weightGrams as number)
			: 0,
		created_at:
			p.createdAt || new Date(Date.UTC(2026, 0, 1, 0, 0, idx)).toISOString(),
	}));

	const imageRows = products.flatMap((p) => {
		const images = Array.isArray(p.images) ? p.images : [];
		return images.map((img, idx) => ({
			source_id: p.sourceId,
			url: img.url,
			is_primary: idx === 0,
		}));
	});

	const brandsJson = Buffer.from(JSON.stringify(brandRows), "utf-8").toString(
		"base64",
	);
	const categoriesJson = Buffer.from(
		JSON.stringify(categories.map((name) => ({ name }))),
		"utf-8",
	).toString("base64");
	const productsJson = Buffer.from(
		JSON.stringify(productRows),
		"utf-8",
	).toString("base64");
	const imagesJson = Buffer.from(JSON.stringify(imageRows), "utf-8").toString(
		"base64",
	);

	const sql = `-- Auto-generated by packages/api/scripts/generate-seed-from-products.ts
-- Source: products.json

BEGIN;

DELETE FROM ecom_vit_sales;
DELETE FROM ecom_vit_cart_item;
DELETE FROM ecom_vit_payment;
DELETE FROM ecom_vit_order_detail;
DELETE FROM ecom_vit_cart;
DELETE FROM ecom_vit_order;
DELETE FROM ecom_vit_purchase;
DELETE FROM ecom_vit_product_image;
DELETE FROM ecom_vit_product;
DELETE FROM ecom_vit_customer;
DELETE FROM ecom_vit_category;
DELETE FROM ecom_vit_brand;
DELETE FROM ecom_vit_user;

INSERT INTO ecom_vit_user (username, is_approved, created_at)
VALUES
  ('admin', true, NOW()),
  ('staff1', true, NOW()),
  ('staff2', false, NOW());

CREATE TEMP TABLE seed_brand (name text, logo_url text) ON COMMIT DROP;
INSERT INTO seed_brand (name, logo_url)
SELECT x.name, x.logo_url
FROM jsonb_to_recordset(convert_from(decode('${brandsJson}', 'base64'), 'utf8')::jsonb)
AS x(name text, logo_url text);

INSERT INTO ecom_vit_brand (name, logo_url, created_at, deleted_at)
SELECT name, logo_url, NOW(), NULL::timestamp
FROM seed_brand;

CREATE TEMP TABLE seed_category (name text) ON COMMIT DROP;
INSERT INTO seed_category (name)
SELECT x.name
FROM jsonb_to_recordset(convert_from(decode('${categoriesJson}', 'base64'), 'utf8')::jsonb)
AS x(name text);

INSERT INTO ecom_vit_category (name, created_at, deleted_at)
SELECT name, NOW(), NULL::timestamp
FROM seed_category;

CREATE TEMP TABLE seed_product (
  source_id integer,
  name text,
  slug text,
  description text,
  status text,
  discount integer,
  amount text,
  potency text,
  stock integer,
  price integer,
  daily_intake integer,
  category text,
  brand text,
  tags jsonb,
  is_featured boolean,
  ingredients jsonb,
  seo_title text,
  seo_description text,
  name_mn text,
  weight_grams integer,
  created_at timestamptz
) ON COMMIT DROP;

INSERT INTO seed_product (
  source_id, name, slug, description, status, discount, amount, potency, stock, price, daily_intake,
  category, brand, tags, is_featured, ingredients, seo_title, seo_description, name_mn, weight_grams, created_at
)
SELECT
  x.source_id,
  x.name,
  x.slug,
  x.description,
  x.status,
  x.discount,
  x.amount,
  x.potency,
  x.stock,
  x.price,
  x.daily_intake,
  x.category,
  x.brand,
  COALESCE(x.tags, '[]'::jsonb),
  x.is_featured,
  COALESCE(x.ingredients, '[]'::jsonb),
  x.seo_title,
  x.seo_description,
  x.name_mn,
  COALESCE(x.weight_grams, 0),
  x.created_at::timestamptz
FROM jsonb_to_recordset(convert_from(decode('${productsJson}', 'base64'), 'utf8')::jsonb)
AS x(
  source_id integer,
  name text,
  slug text,
  description text,
  status text,
  discount integer,
  amount text,
  potency text,
  stock integer,
  price integer,
  daily_intake integer,
  category text,
  brand text,
  tags jsonb,
  is_featured boolean,
  ingredients jsonb,
  seo_title text,
  seo_description text,
  name_mn text,
  weight_grams integer,
  created_at text
);

INSERT INTO ecom_vit_product (
  name, slug, description, status, discount, amount, potency, stock, price, daily_intake,
  category_id, brand_id, tags, is_featured, ingredients, seo_title, seo_description, name_mn, weight_grams,
  created_at, deleted_at
)
SELECT
  LEFT(p.name, 256),
  LEFT(p.slug, 256),
  p.description,
  p.status,
  p.discount,
  LEFT(p.amount, 256),
  LEFT(p.potency, 256),
  p.stock,
  p.price,
  p.daily_intake,
  c.id,
  b.id,
  p.tags,
  p.is_featured,
  p.ingredients,
  LEFT(p.seo_title, 256),
  LEFT(p.seo_description, 512),
  LEFT(p.name_mn, 256),
  p.weight_grams,
  p.created_at,
  NULL::timestamp
FROM seed_product p
JOIN ecom_vit_brand b ON b.name = p.brand
JOIN ecom_vit_category c ON c.name = p.category
ORDER BY p.created_at ASC, p.source_id ASC;

CREATE TEMP TABLE seed_product_id_map AS
SELECT p.id AS product_id, s.source_id
FROM ecom_vit_product p
JOIN seed_product s ON s.slug = p.slug;

CREATE TEMP TABLE seed_image (source_id integer, url text, is_primary boolean) ON COMMIT DROP;
INSERT INTO seed_image (source_id, url, is_primary)
SELECT x.source_id, x.url, x.is_primary
FROM jsonb_to_recordset(convert_from(decode('${imagesJson}', 'base64'), 'utf8')::jsonb)
AS x(source_id integer, url text, is_primary boolean);

INSERT INTO ecom_vit_product_image (product_id, url, is_primary, created_at, deleted_at)
SELECT m.product_id, LEFT(i.url, 512), i.is_primary, NOW(), NULL::timestamp
FROM seed_image i
JOIN seed_product_id_map m ON m.source_id = i.source_id;

COMMIT;
`;

	writeFileSync(outputPath, sql, "utf-8");
	mkdirSync(resolve(root, "generated"), { recursive: true });
	writeFileSync(
		reportPath,
		`${JSON.stringify(
			{
				generatedAt: new Date().toISOString(),
				productCount: products.length,
				brandCount: brands.length,
				categoryCount: categories.length,
				imageRows: imageRows.length,
				outputPath,
			},
			null,
			2,
		)}\n`,
		"utf-8",
	);

	console.log(
		JSON.stringify(
			{
				productCount: products.length,
				brandCount: brands.length,
				categoryCount: categories.length,
				imageRows: imageRows.length,
			},
			null,
			2,
		),
	);
}

main();
